"""add user ownership to usage records

Revision ID: be8e534fc427
Revises: c205d31c4220
Create Date: 2026-08-12 19:04:31.446285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8e534fc427'
down_revision: Union[str, Sequence[str], None] = 'c205d31c4220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'usage_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_records', type_='foreignkey')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_column('usage_records', 'user_id')
    # ### end Alembic commands ###
